"""URJ-004 baseline: the complete current schema.

Revision 0. This is a *squash-to-baseline* migration: instead of idiomatic
``op.create_table`` calls, it replays an audited ``pg_dump --schema-only`` of the
canonical schema (``0001_baseline_schema.sql``). This is deliberate and is the only
approach that reproduces the legacy schema **byte-for-byte** — the legacy chain
(``database/00..44``) builds many tables via incremental ``ALTER ADD COLUMN`` across
files, so a single-CREATE reconstruction would produce a different physical column
order and fail the ``scripts/verify_schema_parity.sh`` diff.

The baseline SQL is generated by ``scripts/verify_schema_parity.sh --write-baseline``
and must never be hand-edited. Parity between this migration and the legacy
construction path is proven by that script (and enforced in CI).

Revision ID: 0001
Revises:
Create Date: 2026-07-07
"""

from pathlib import Path

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

_BASELINE_SQL = Path(__file__).with_name("0001_baseline_schema.sql")


def upgrade() -> None:
    sql = _BASELINE_SQL.read_text()
    # psycopg2 executes the whole multi-statement dump in one call.
    op.get_bind().exec_driver_sql(sql)


def downgrade() -> None:
    # Baseline is all-or-nothing: tear the public schema down to empty so the
    # migration is reversible for tests / clean re-applies. DROP SCHEMA CASCADE
    # also removes Alembic's own alembic_version table, so recreate it AND restore
    # the current version row ('0001'): Alembic finalizes the downgrade by deleting
    # that row and asserts exactly one row is matched, so it must be present.
    # NOTE: this also drops the schema's default PUBLIC grants; that is fine for the
    # CI/test reversibility check (the only place downgrade is exercised), but a
    # downgrade in a real environment would need grants/ownership re-applied.
    op.execute("DROP SCHEMA public CASCADE")
    op.execute("CREATE SCHEMA public")
    op.execute(
        "CREATE TABLE public.alembic_version ("
        "version_num VARCHAR(32) NOT NULL "
        "CONSTRAINT alembic_version_pkc PRIMARY KEY)"
    )
    op.execute("INSERT INTO public.alembic_version (version_num) VALUES ('0001')")
